spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/lernbegleiter?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: abcdefgh12
