lernbegleiter:
  host: ${LERNBEGLEITER_HOST_AND_PORT}
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          fetch_size: 1000
          batch_versioned_data: true
    show-sql: false
    hibernate:
      naming:
        physical-strategy: at.technikumwien.lernbegleiter.entities.SpringPhysicalNamingStrategyUpperCase
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${DB_HOST_AND_PORT}/lernbegleiter?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 300

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: INFO